DROP TABLE STUDENT CASCADE CONSTRAINTS PURGE;
CREATE TABLE STUDENT(
  STUDENT_ID INTEGER,
  STUDENT_NAME VARCHAR(50),
  PRIMARY KEY(STUDENT_ID)
);

DROP TABLE ZIP CASCADE CONSTRAINTS PURGE;
CREATE TABLE ZIP(
  ZIPCODE VARCHAR(7),
  STREET VARCHAR(100),
  STATE VARCHAR(30),
  PRIMARY KEY(ZIPCODE,STREET)
);

DROP TABLE STUDENT_ADDR CASCADE CONSTRAINTS PURGE;
CREATE TABLE STUDENT_ADDR(
  ZIPCODE VARCHAR(7),
  STREET VARCHAR(100),
  STUDENT_ID INTEGER,
  FOREIGN KEY(ZIPCODE) REFERENCES ZIP(ZIPCODE),
  FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  FOREIGN KEY(STREET) REFERENCES ZIP(STREET)
);

DROP TABLE PRIOR_SCHOOL CASCADE CONSTRAINTS PURGE;
CREATE TABLE PRIOR_SCHOOL(
  PRIOR_SCHOOL_ID INTEGER,
  PRIOR_SCHOOL_ADDR VARCHAR(100),
  PRIMARY KEY(PRIOR_SCHOOL_ID)
);

DROP TABLE APP_REFERENCE CASCADE CONSTRAINTS PURGE;
CREATE TABLE APP_REFERENCE(
  REFERENCE_ID INTEGER,
  REF_NAME varchar(100),
  REF_INSTITUTE varchar(100),
  REF_STATEMENT varchar(500),
  PRIMARY KEY(REFERENCE_ID)
);


DROP TABLE APPLICATION CASCADE CONSTRAINTS PURGE;
CREATE TABLE APPLICATION(
  APP_NO INTEGER,
  APP_YEAR INTEGER,
  STUDENT_ID INTEGER,
  REFERENCE_ID INTEGER,
  PRIMARY KEY(APP_NO,APP_YEAR),
  FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  FOREIGN KEY(REFERENCE_ID) REFERENCES APP_REFERENCE(REFERENCE_ID)
);

DROP TABLE STUDENT_GPA CASCADE CONSTRAINTS PURGE;
CREATE TABLE STUDENT_GPA(
  STUDENT_ID INTEGER,
  PRIOR_SCHOOL_ID INTEGER,
  GPA INTEGER,
  FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
  FOREIGN KEY(PRIOR_SCHOOL_ID) REFERENCES PRIOR_SCHOOL(PRIOR_SCHOOL_ID)
);
